#!/bin/bash

KPIN_VERSION='1.6.3'

if ! docker image inspect "ghcr.io/kronostechnologies/kpin:${KPIN_VERSION}" &> /dev/null; then
  docker pull "ghcr.io/kronostechnologies/kpin:${KPIN_VERSION}"
fi

declare -a FLAGS=( --rm --read-only )

if [[ -f "${HOME}/.config/kpin.yaml" ]]; then
  FLAGS+=( -v "${HOME}/.config/kpin.yaml":/root/.config/kpin.yaml )
fi

if [[ -d "${HOME}/.aws" ]]; then
  FLAGS+=( -v "${HOME}/.aws":/root/.aws )
fi

if [[ -t 1 ]]; then
  FLAGS+=( --tty )
fi

for V in $(env | grep "^AWS_" | awk -F= '{print $1}'); do
  if [[ -n "${!V}" ]]; then
    FLAGS+=( -e ${V}="${!V}" )
  fi
done

docker run "${FLAGS[@]}" "ghcr.io/kronostechnologies/kpin:${KPIN_VERSION}" "$@"
